spring:
  datasource:
    url: jdbc:h2:file:~/spring-boot
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true